name: Print Software Versions
on: 
  push:
      branches: main
jobs:
  printSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
          - name: Print Python Version
            run: python --version
          - name: Print Java Version
            run: java --version
          - name: Print Node Version
            run: node --version            
  printDatabaseVersions:
    runs-on: ubuntu-latest
    steps:
          - name: Print MySQL Version
            run: mysql --version
          - name: Print PostgreSQL Version
            run: psql --version 
          - name: Print SQLite Version
            run: sqlite3 --version            
